apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgAASP2BIsXQNVKmEcEUY7McBDvCrjBYeAtInkV0LEdfK0OinmIATnwjjb3brnY2Kbsu9WIr9ZurOpOPuzAIWeIvGKttwSIT39qT1zAtu2xW5K4wzL5IgWcQ7aqtsgHbRc8vVlBEeowPrV9yMo23CIOzT13cIu6IfFnVFlE0XiIzaUNh8tMpxu2wZVh/CqBnRc+cs9YfbDfp7+BJRKAof9R4iuXsWKkRUhWHmrvd3JrhMRXDEpbog9kh62jrljQoUuJCiIZDNSG0+yUv6p6eIrpk16OZ5QccBzN0jTQOufiS1ZzXGa5rw6x7qRsPsiIgdjd42vlvCFubQ6YY4e9r/SpnlFalx29IbaZqntle+nmv4hg/ppsPl9tR4XKTCKwKDP/H/JCNdD8yWR6fLgkqkYD1dG3TFPwoTxERApTffm52w8lwU7Bv3rdjPWlFdJRu0mYlU/rffVddhKNWgs7Yyfm+jU5S+1ptD4HAkIPeVCZ5sLOwDmcwa5fPRUB0+0dNtNfbSOJF5Gm2QFUfAJ5GdwTFGpK3AFwAE0hZPkSfjr4cno/P5/b1Ddlnbx7pmIMABa1JtnDI6Mo7wtCGnGnm2Ag9/cvH4KzoSJ6sv8TOXBNamTt0L+gwm5hgt3nmJA/FfkeRULfnvJ+dY9VaY6ZgjX7hCY7TXMqVdKnXm9gSjEPF658T657yKGIKGFix//BW+b3dAht2UqkVvvgxtmjbU8MiB6RKGXjdDOKVuRO1ffRJDLfbfnqES3Yr
    username: AgClA406TNOQHI+o7lchKQFYxBNGy+aHMUSYGHex/Y7k9K7TT7lIGxS+RR+naMUviON1pxA9ns866CoXwPrdz8zsySgYk9GtoG5adiwHAtJ7l/0qSOt1dhv8rwMgE/bqB7QhTijz6/ovdUN5VpCwPBQoZ8kKLTBoF4lhBioR/KMqlu28eM78lLUTrCxTNoo5GF2B681i3T5fXkk4JK+nd9+CUOGuH8Fy0tFjZlLO1sY3Gl7FgwO/QcFw2Ijip/IelvOwNrqMha2ZxhvKti3Qg4r7OFFEaEDoMkBCmCEwBciazsxAqNCvSD3hQhX1LN4kbcv6pDEuxQKJwjcl7npp1nwfhCgL2DPoHT/N8YXE6lZajsCM3UcNdw96m4SEbGU7iLXkf2qbEvLq5/A+bJSliUwv6hg+3aFjLk/AnspBK7yFtJaevUdUrKy1lkaOD3GqJmFwKn8RfSxLcT6xH+UJM2/t++r+odoySguZ3vbZjcyJxQZOeHw2C5dn8qOUMO3ycSrD2weEOeSxBJdVpfzLPGkHm+Cjpmtfeh2U9UC6YSG/Bvvjkjh+AjIRyIIsCpptSxW4HGb0vIzhX8UpoPqG9U1Iy3r077bkPWxGXuM5z1PInrFM0LGZvRwUD5zG28lu2n1HWf7SjnP9Ph+UFB6s5TnGLJkt/KK3yIPVDcjGEPYZDWtdL9rIJBbu5qNrM/AxC1vwUQQI4g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

