apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo-ace
data:
  branch: ocp47-2021-2
  host: github.com
  org: cloudpaks-gitops-ace
  owner: joe4k
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/cloudpaks-gitops-ace/multi-tenancy-gitops-apps.git
